---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wdjyq4olhx2/public_html/alientech
    - export NODE_VERSION=18
    - npm install --production=false
    - npm run build
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R dist/* $DEPLOYPATH/
